EmprestimoLivros/Models/EmprestimoModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace EmprestimoLivros.Models
{
    public class EmprestimoModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Nome do recebedor - Preenchimento obrigatório!")]
        public string Recebedor { get; set; }

        [Required(ErrorMessage = "Nome do fornecedor - Preenchimento obrigatório!")]
        public string Fornecedor { get; set; }

        [Required(ErrorMessage = "Livro emprestado - Preenchimento obrigatório!")]
        public string LivroEmprestado { get; set; }

        public DateTime DataUltimaAtualizacao { get; set; } = DateTime.Now;
    }
}

EmprestimoLivros/Models/ErrorViewModel.cs
namespace EmprestimoLivros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmprestimoLivros/Controllers/EmprestimoController.cs
using EmprestimoLivros.Data;
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmprestimoLivros.Controllers
{
    public class EmprestimoController : Controller
    {

        private readonly ApplicationDbContext _db;

        public EmprestimoController(ApplicationDbContext db) 
        { 
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<EmprestimoModel> emprestimos = _db.Emprestimos;
            return View(emprestimos);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(EmprestimoModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimos.Add(emprestimo);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Registro incluido com sucesso!";

                return RedirectToAction("Index");
            }

            TempData["MensagemErro"] = "Houve um erro ao incluir um novo empréstimo!";
            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimoModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id == id);

            if(emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Editar(EmprestimoModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimos.Update(emprestimo);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Registro alterado com sucesso!";

                return RedirectToAction("Index");
            }

            TempData["MensagemErro"] = "Houve um erro ao editar o empréstimo!";

            return View(emprestimo);
        }

        [HttpGet]
        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimoModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id == id);

            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Excluir(EmprestimoModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                TempData["MensagemErro"] = "Houve um erro ao excluir um empréstimo!";
                return NotFound();   
            }

            _db.Emprestimos.Remove(emprestimo);
            _db.SaveChanges();

            TempData["MensagemSucesso"] = "Registro exclído com sucesso!";

            return RedirectToAction("Index");
        }
    }
}

EmprestimoLivros/Controllers/HomeController.cs
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimoLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmprestimoLivros/Views/Emprestimo/Cadastrar.cshtml
@model EmprestimoModel
@{
    ViewData["Title"] = "Cadastrar Empréstimo";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-3 text-center">
        <h1 class="text-light">Cadastro de Empréstimos</h1>
    </div>


    <form method="post" asp-controller="Emprestimo" asp-action="Cadastrar">
        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for ="Recebedor"></span>
        </div>


        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="LivroEmprestado" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="LivroEmprestado" placeholder="Qual livro está sendo emprestado?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>
       
        
    </form>

</div>

EmprestimoLivros/Views/Emprestimo/Editar.cshtml
@model EmprestimoModel
@{
    ViewData["Title"] = "Editar Empréstimo";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-3 text-center">
        <h1 class="text-light">Edição de Empréstimos</h1>
    </div>


    <form method="post" asp-controller="Emprestimo" asp-action="Editar">
        <input type="hidden" asp-for=Id/>
        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>


        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="LivroEmprestado" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="LivroEmprestado" placeholder="Qual livro está sendo emprestado?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>


    </form>

</div>

EmprestimoLivros/Views/Emprestimo/Excluir.cshtml
@model EmprestimoModel
@{
    ViewData["Title"] = "Excluir Empréstimo";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-3 text-center">
        <h1 class="text-light">Exclusão de Empréstimos</h1>
    </div>


    <form method="post" asp-controller="Emprestimo" asp-action="Excluir">
        <input type="hidden" asp-for=Id />

        <h3 class="text-light text-center" >Confirma a exclusão do empréstimo abaixo?</h3>

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?" disabled>
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>


        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o livro?" disabled>
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="LivroEmprestado" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="LivroEmprestado" placeholder="Qual livro está sendo emprestado?" disabled>
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>


    </form>

</div>

EmprestimoLivros/Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimoModel>


<div class="container-fluid">
    <div class="d-flex justify-content-between align-itens-center mb-4">
        <h2>Empréstimos</h2>
        <a class="btn btn-success" asp-controller="Emprestimo" asp-action="Cadastrar" style="width: 320px; height: 38px; display: inline-flex; align-items: center;"><i class="bi bi-file-earmark-plus mx-2"></i>Cadastrar novo empréstimo</a>
    </div>

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-light text-center" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger text-light text-center" role="alert">
            @TempData["MensagemErro"]
        </div>
    }


    <table id="Emprestimos" class="table table-light table-hover mt-2" style="font-size: 13px;" >
        <thead>
            <tr>
                <th scope="col">Recebedor</th>
                <th scope="col">Fornecedor</th>
                <th scope="col">Livro</th>
                <th scope="col">Última Atualização</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null)
            {
                @foreach(var emprestimo in Model)
                {
                    <tr>
                        <th scope="row">@emprestimo.Recebedor</th>
                        <td scope="row">@emprestimo.Fornecedor</td>
                        <td scope="row">@emprestimo.LivroEmprestado</td>
                        <td scope="row">@emprestimo.DataUltimaAtualizacao</td>
                        <td>
                            <a class="btn btn-warning mx-2" asp-controller="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id" style="width: 115px; height: 28px; display: inline-flex; align-items: center; justify-content: center; text-transform: none;"><i class="bi bi-pencil-square mx-2"></i>Editar</a>
                            <a class="btn btn-danger mx-2" asp-controller="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id" style="width: 120px; height: 28px; display: inline-flex; align-items: center; justify-content: center; text-transform: none;"><i class="bi bi-trash mx-2"></i> Excluir</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

EmprestimoLivros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-6">Empréstimos Online</h1>
    <p>Abra um livro, deixe-se levar. Um novo mundo você vai encontrar!</p>
    <div>
        <img src="/img/book.png"/>
    </div>
</div>

EmprestimoLivros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Emprestimo de Livros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/materia.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimoLivros.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3" style="padding: 5px 10px;">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index" style="font-size: 18px;">Emprestimo de Livros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Emprestimo" asp-action="Index"><i class="bi bi-journals"></i> Empréstimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2024 - EmprestimoLivros - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>